name: com.walturn
description: A simple Flutter application that shows a text of a Cat with a clock icon. When the text is clicked, it changes to a Dog with a person icon.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.3
  mocktail: ^0.3.0

flutter:
  uses-material-design: true